version: '3'

services:
  web:
    build: .
    command: bash -c "python src/manage.py makemigrations && python src/manage.py migrate && python src/manage.py loaddata fixtures/data.json && python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - EMAIL_HOST_USER=example@gmail.com
      - EMAIL_HOST_PASSWORD=<password>
