# Generated by Django 3.0.7 on 2020-06-09 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200609_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
