# Generated by Django 3.0.7 on 2020-06-09 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200609_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
