# Generated by Django 3.0.7 on 2020-07-10 11:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200708_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
